apiVersion: v2
name: rocktemplate
home: "https://github.com/spidernet-io/rocktemplate"
# application or library
type: application
# no need to modify this version , CI will auto update it with /VERSION
version: 0.1.0
# This field is informational, and has no impact on chart version calculations .
# Leaving it unquoted can lead to parsing issues in some cases
# no need to modify this version , CI will auto update it with /VERSION
appVersion: "0.1.0"
kubeVersion: ">= 1.16.0-0"
description: rocktemplate
sources:
  - "https://github.com/spidernet-io/rocktemplate"
keywords:
  - rocktemplate
maintainers:
  - name: spidernet-io
    url: https://github.com/spidernet-io
